In [25]:
import pandas as pd
from pathlib import Path
import os

In [26]:
df = pd.read_csv("../data/main/edc_all_artists.csv")
df.drop_duplicates(inplace=True)
df.head()

   year            artist
0  2024             1080p
1  2024  A Shade of Black
2  2024           Aaron K
3  2024             Abana
4  2024        D. Zeledon

In [ ]:
if "year" in df.columns:
    df = df.drop(columns=["year"])

# Drop duplicates after removing the year column
df = df.drop_duplicates()
print(f"Unique artists count: {len(df)}")

In [ ]:
# Save the deduplicated data
df.to_csv("../data/main/edc_artists_no_duplicates.csv", index=False)
print("Saved to ../data/main/edc_artists_no_duplicates.csv")

In [29]:
df.count()

artist    1476
dtype: int64

In [30]:
df1 = pd.read_csv("../data/main/edc_artists_no_duplicates.csv")
df1.drop_duplicates(inplace=True)

In [ ]:
df1.drop_duplicates()

                artist
0                1080p
1     A Shade of Black
2              Aaron K
3                Abana
4           D. Zeledon
...                ...
1468       Willie Pake
1469           X CLUB.
1470            Xandra
1471               YDG
1473  Yoji Biomehanika

[1046 rows x 1 columns]

In [34]:
df1["artist"].nunique()
df1

                artist
0                1080p
1     A Shade of Black
2              Aaron K
3                Abana
4           D. Zeledon
...                ...
1468       Willie Pake
1469           X CLUB.
1470            Xandra
1471               YDG
1473  Yoji Biomehanika

[1046 rows x 1 columns]