In [15]:
import pandas as pd
import numpy as np
import os

In [16]:
main_dir = "../data/main"
artists_stats = pd.read_csv(os.path.join(main_dir, "edc_artist_stats_cleaned.csv"))
artists_count = pd.read_csv(os.path.join(main_dir, "artist_counts_2022_2025.csv"))
artists_agencies = pd.read_csv(os.path.join(main_dir, "artists_agency.csv"))

In [17]:
merged_stats_count = pd.merge(artists_stats, artists_count, on="artist", how="left")
merged_all = pd.merge(merged_stats_count, artists_agencies, on="artist", how="left")
merged_all.head()

,artist,followers,streams,playlists,playlist reach,charts,shazams,videos,views,dj supports,total_appearances,years_played,agency
0,1080p,6,5986,1,641,0,17,45,9800,0,1.0,[np.int64(2024)],insomniac
1,a shade of black,0,15100,0,11000,7,0,0,0,0,1.0,[np.int64(2024)],NaN
2,aaron k,1,2163,0,0,1,4,2,0,0,2.0,"[np.int64(2024), np.int64(2025)]",insomniac
3,abana,7710,468000,175,4220000,60,15300,110,1890000,93,3.0,"[np.int64(2022), np.int64(2023), np.int64(2024)]",insomniac
4,d. zeledon,5776,69600,25,218000,18,764,31,9672,58,1.0,[np.int64(2024)],insomniac

In [18]:
# Convert total_appearances to int, replace 0 with 1
merged_all['total_appearances'] = merged_all['total_appearances'].fillna(0).astype(int)
merged_all['total_appearances'] = merged_all['total_appearances'].replace(0, 1)

# Clean years_played to show only years (e.g., "2024, 2025" instead of "[np.int64(2024)]")
def clean_years(val):
    if pd.isna(val) or val == 0:
        return ""
    val_str = str(val)
    # Extract all 4-digit years from the string
    import re
    years = re.findall(r'\b(20\d{2})\b', val_str)
    return ', '.join(years) if years else val_str

merged_all['years_played'] = merged_all['years_played'].apply(clean_years).astype(str)

merged_all.head()

,artist,followers,streams,playlists,playlist reach,charts,shazams,videos,views,dj supports,total_appearances,years_played,agency
0,1080p,6,5986,1,641,0,17,45,9800,0,1,2024,insomniac
1,a shade of black,0,15100,0,11000,7,0,0,0,0,1,2024,NaN
2,aaron k,1,2163,0,0,1,4,2,0,0,2,"2024, 2025",insomniac
3,abana,7710,468000,175,4220000,60,15300,110,1890000,93,3,"2022, 2023, 2024",insomniac
4,d. zeledon,5776,69600,25,218000,18,764,31,9672,58,1,2024,insomniac

In [19]:
merged_all = merged_all.drop_duplicates()
merged_all.head()

,artist,followers,streams,playlists,playlist reach,charts,shazams,videos,views,dj supports,total_appearances,years_played,agency
0,1080p,6,5986,1,641,0,17,45,9800,0,1,2024,insomniac
1,a shade of black,0,15100,0,11000,7,0,0,0,0,1,2024,NaN
2,aaron k,1,2163,0,0,1,4,2,0,0,2,"2024, 2025",insomniac
3,abana,7710,468000,175,4220000,60,15300,110,1890000,93,3,"2022, 2023, 2024",insomniac
4,d. zeledon,5776,69600,25,218000,18,764,31,9672,58,1,2024,insomniac

In [20]:
# Convert columns to numeric values
numeric_cols = ['followers', 'streams', 'playlists', 'playlist reach', 
                'charts', 'shazams', 'videos', 'views', 'dj supports', 'total_appearances']

for col in numeric_cols:
    merged_all[col] = pd.to_numeric(merged_all[col], errors='coerce').fillna(0).astype(int)

# Verify the conversions
print(merged_all[numeric_cols].dtypes)

followers            int64
streams              int64
playlists            int64
playlist reach       int64
charts               int64
shazams              int64
videos               int64
views                int64
dj supports          int64
total_appearances    int64
dtype: object

In [21]:
merged_all.drop_duplicates()
# merged_all.count

,artist,followers,streams,playlists,playlist reach,charts,shazams,videos,views,dj supports,total_appearances,years_played,agency
0,1080p,6,5986,1,641,0,17,45,9800,0,1,2024,insomniac
1,a shade of black,0,15100,0,11000,7,0,0,0,0,1,2024,NaN
2,aaron k,1,2163,0,0,1,4,2,0,0,2,"2024, 2025",insomniac
3,abana,7710,468000,175,4220000,60,15300,110,1890000,93,3,"2022, 2023, 2024",insomniac
4,d. zeledon,5776,69600,25,218000,18,764,31,9672,58,1,2024,insomniac
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383,decoder,32299,113000,0,147000,27,0,0,22800,84,1,,insomniac
1384,4b,706000,201000000,0,70100000,424,604000,1210000,363000000,6272,1,,insomniac
1385,4b,706000,201000000,0,70100000,424,604000,1210000,363000000,6272,1,,wasserman
1386,malaa,1220000,3100000000,10800,148000000,876,3170000,63500,682000000,10500,1,2023,insomniac
1387,malaa,1220000,3100000000,10800,148000000,876,3170000,63500,682000000,10500,1,2023,wasserman

In [22]:
merged_all.to_csv("../data/main/COMPLETE_edc_artist_and_stats.csv", index=False)

In [9]:
# Check dataframe shape and content
print(f"Rows: {len(merged_all)}, Columns: {len(merged_all.columns)}")
merged_all.head()

Rows: 1388, Columns: 13

,artist,followers,streams,playlists,playlist reach,charts,shazams,videos,views,dj supports,total_appearances,years_played,agency
0,1080p,6,5986,1,641,0,17,45,9800,0,1,2024,insomniac
1,a shade of black,0,15100,0,11000,7,0,0,0,0,1,2024,NaN
2,aaron k,1,2163,0,0,1,4,2,0,0,2,"2024, 2025",insomniac
3,abana,7710,468000,175,4220000,60,15300,110,1890000,93,3,"2022, 2023, 2024",insomniac
4,d. zeledon,5776,69600,25,218000,18,764,31,9672,58,1,2024,insomniac

In [10]:
# Check the data type of years_played
print(merged_all['years_played'].dtype)
print(merged_all['years_played'].head(10))

object
0                2024
1                2024
2          2024, 2025
3    2022, 2023, 2024
4                2024
5    2022, 2023, 2024
6    2022, 2023, 2024
7    2022, 2023, 2024
8    2022, 2023, 2024
9          2022, 2024
Name: years_played, dtype: object

some artist are duplicate because they have 2 agencies, insomniac and another one. Delete the dup that has agency = "insomniac"